title:        abstrus codes
url:          http://cblegare.github.io
author:       Charles Bouchard-Légaré

meta:
    cblegare:
        name:     Charles Bouchard-Légaré
        github:   cblegare

source:       .
destination:  ./_site
markdown:     kramdown
pygments:     true
permalink:    /:categories/:title.html
future:       false
